### ISSUE TITLE
Language autodetection

### ISSUE THREAD

**Issue by mjaniec2013** [itseco/to-google-translate#11]
It would be great to allow auto-detection of the phrase being translated.

**Comment by GiovanniSM20** [comment]
II agree with you @mjaniec2013 , in fact I was now going to fork the repository because it automatically picks up the text in English (only) and passes to Spanish...

**Comment by itseco** [comment]
The new version 3.0 is now in queue to review from Firefox Addon Team. The new version has the pageLang as "auto" for default.

**Comment by itseco** [comment]
@mjaniec2013 @GiovanniSM20 Version 3.0 is now available on Firefox Addons web site.
