### ISSUE TITLE
cannot use zh-CN or zh-TW cause enter '-' is not allowed

### ISSUE THREAD

**Issue by gccpacman** [itseco/to-google-translate#15]
The url for translate to 'zh-CN' is [https://translate.google.com/#en/zh-CN/Hello%20World](https://translate.google.com/#en/zh-CN/Hello%20World) ,  and the '-' is not allowed in the `Translate Text` and `Text to speech` so these languages are not working.

**Comment by itseco** [comment]
The new version is now in Queue to review from Firefox Addon Team. The new version fix this issue.

**Comment by itseco** [comment]
Version 3.0 is now available on Firefox Addons web site.

**Comment by gccpacman** [comment]
Great work! Thanks a lot! @itsecurityco
