### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by happysurf** [itseco/to-google-translate#2]
This is a great extension because is simple, web extensions ready and works on text area.
What is the way for set the translation language to AUTO DETECT?
The selection number words is very limited (only 150/5000) why?
In addition I suggest to add in context menu the option for translate the entire page if nothing is selected.
Thanks.

**Comment by itseco** [comment]
Hello, the autodetect will be added in the next release, I'll upload it in this week and I hope Mozilla team approves the changes quickly.

Regards

**Comment by itseco** [comment]
UPDATE: I new version with 'auto detect' support has been submitted. We must wait a few days for Mozilla to review and aproves the changes.

**Comment by itseco** [comment]
UPDATE, the addon has beed update it. You can find it at https://addons.mozilla.org/en-US/firefox/addon/to-google-translate/

Regards!
