### ISSUE TITLE
Opinion need: use translate.google.cn for zh-CN

### ISSUE THREAD

**Issue by ivysrono** [itseco/to-google-translate#3]
google.com is blocked in China.
We use https://translate.google.cn/

**Comment by itseco** [comment]
Thank you for the report. I will work on a solution and will update the issue when has been fix it.

**Comment by itseco** [comment]
The new version 3.0 is now in queue to review from Firefox Addon Team. The new version fix this issue.

**Comment by itseco** [comment]
@ivysrono Version 3.0 is now available on Firefox Addons web site.
