### ISSUE TITLE
How to disable the Text To Speech?

### ISSUE THREAD

**Issue by ivysrono** [itseco/to-google-translate#4]
I do not need it.

**Comment by itseco** [comment]
Currently you can not. I will think in the possibility of make it optional.

**Comment by rshadow** [comment]
Maybe empty field disable this feature? 
And clicking on the menu item immediately opens the translator. It's so hard to aim at the extra menu.

**Comment by itseco** [comment]
The new version 3.0 is now in queue to review from Firefox Addon Team. The new version has an option to enable/disable Text To Speech and Translate Text.

**Comment by itseco** [comment]
@ivysrono @rshadow Version 3.0 is now available on Firefox Addons web site.
