### ISSUE TITLE
No options at all.

### ISSUE THREAD

**Issue by 0xCA** [itseco/to-google-translate#5]
Well, I clicked "options" and got nothing behind it. So I can't use it. Installed from addons.mozilla.org
![image](https://user-images.githubusercontent.com/11984323/26901571-c7a07f08-4bef-11e7-8f66-4a0440a48466.png)

**Comment by itseco** [comment]
Hello, What version of Firefox and what OS are you using? Thanks

**Comment by 0xCA** [comment]
Hello. Latest FF and latest Win10 Pro.

**Comment by itseco** [comment]
You need restart FF and scroll down to see the options section. Please let me know if this work.

Regards
![tgt1](https://user-images.githubusercontent.com/1725054/26903603-f8d7ccfa-4bab-11e7-9607-827bec2a14cf.png)
![tgt3](https://user-images.githubusercontent.com/1725054/26903604-f8dbb96e-4bab-11e7-8c37-0f7f120cce9a.png)

**Comment by 0xCA** [comment]
I have nearly same specs on my system. As for FF, absolutely same version.
And options screen is still empty, after restart, reboot and re-install.
