### ISSUE TITLE
License issues

### ISSUE THREAD

**Issue by davidhedlund** [itseco/to-google-translate#7]
Previously I recommended a modification of the GPL guidelines which was wrong. Now I've had a fresh look on the actual license.

# From https://www.mozilla.org/en-US/MPL/2.0/

Exhibit A - Source Code Form License Notice

> This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0. If a copy of the MPL was not distributed with this file, You can obtain one at https://mozilla.org/MPL/2.0/.

If it is not possible or desirable to put the notice in a particular file, then You may include the notice in a location (such as a LICENSE file in a relevant directory) where a recipient would be likely to look for such a notice.

You may add additional accurate notices of copyright ownership.

# Requests

* Can you please download https://www.mozilla.org/media/MPL/2.0/index.txt, rename the file from index.txt to LICENSE, and put it in the root directory for your add-on?

* You can copy pre-defined headers from https://www.mozilla.org/en-US/MPL/headers/ if you want to use them.

**Comment by davidhedlund** [comment]
Previously I recommended a modification of the GPL guidelines which was wrong. Now I've had a fresh look on the actual license.

From https://www.mozilla.org/en-US/MPL/2.0/

Exhibit A - Source Code Form License Notice

> This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0. If a copy of the MPL was not distributed with this file, You can obtain one at https://mozilla.org/MPL/2.0/.

If it is not possible or desirable to put the notice in a particular file, then You may include the notice in a location (such as a LICENSE file in a relevant directory) where a recipient would be likely to look for such a notice.

You may add additional accurate notices of copyright ownership.


* Can you please download https://www.mozilla.org/media/MPL/2.0/index.txt, rename the file from index.txt to LICENSE, and put it in the root directory for your add-on?

* You can copy pre-defined headers from https://www.mozilla.org/en-US/MPL/headers/ if you want to use them.

**Comment by gluons** [comment]
It looks like he is using new BSD license.

https://github.com/itseco/to-google-translate/blob/1f62c07867245a4cf5e7d5ce366f695ebcb5d42f/translate.js#L5-L6

**Comment by donaldr3** [comment]
Still looking to see if we can get a license fix here. If it is under New BSD could the text of that license please be added?

**Comment by itseco** [comment]
Hello, sorry for the delay., the text of New BSD license has been added.
